#!/bin/bash
#201 Ops Challenge Class 3
#This script will print a greeting and then display the login history of the current machine
greetings () {
echo Hello $1 , here is the login history for this machine
}

greetings Joe
last
